### ISSUE TITLE
Bulb Replacement

### ISSUE THREAD

**Issue by jkastl** [jkastl/rnl8ball#1]
### Pool Ball Rack
- [ ] 4
- [ ] 6
- [ ] 12

### Right side, Special
- [ ] 7

### Right side, Bank shot
- [ ] 14
- [ ] Under pool cue
- [ ] 600
- [ ] 5,000

### 1,000 shoot
- [ ] Left plastic guide

### General
- [ ] Top, right thumper cap
- [ ] 8-ball
- [ ] Left bank shot value
- [ ] 4, right side top
- [ ] Upper, right boob

**Comment by dhcL** [comment]
Also 4, 5, 6, and 12 pool balls center

**Comment by jkastl** [comment]
@dhcL (╯°□°）╯︵ ┻━┻)
